name: Python CI/CD Básico

on:
  push:
    branches:
      - main
      - develop
      - feature/**
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: 1. Checkout del código
      uses: actions/checkout@v4

    - name: 2. Configurar Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: 3. Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        # Instalar Flake8 para Linting y Unittest (si tuvieras dependencias externas)
        pip install flake8

    - name: 4. Verificación de Calidad de Código (Linting)
      run: |
        echo "Ejecutando flake8 para verificar errores y estilo..."
        # El comando verifica el código en la carpeta src/
        flake8 src/ --max-line-length=120 --exclude __init__.py

    - name: 5. Ejecutar Pruebas Automáticas (Testing)
      run: |
        echo "Ejecutando pruebas unitarias..."
        # El comando debe ejecutar el archivo tests/test_lms.py
        python -m unittest tests/test_lms.py

    - name: 6. Build Automático (Simulación)
      # Simulación de un paso de "build" que en una API real podría ser
      # generar artefactos, Docker images, o compilar archivos.
      run: |
        echo "✅ Simulación de Build completada. Artefacto listo para despliegue."
